const FETCH_REQUEST = 'post/FETCH_REQUEST';
const FETCH_SUCCESS = 'post/FETCH_SUCCESS';
const FETCH_ERROR = 'post/FETCH_ERROR';

const DELETE_SUCCESS = 'post/DELETE_SUCCESS';
const ADD_SUCCESS = 'post/ADD_SUCCESS';
const SELECT_AUTHOR = 'post/SELECT_AUTHOR';

export default {
  FETCH_REQUEST,
  FETCH_SUCCESS,
  FETCH_ERROR,
  DELETE_SUCCESS,
  ADD_SUCCESS,
  SELECT_AUTHOR,
};
